using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace Container.Enums
{
    public enum ResultCode
    {
        /// <summary>
        /// The no access
        /// </summary>
        /// <autogeneratedoc />
        [Description("OK")]
        [EnumMember(Value = "200")]
        Ok = 200,

        /// <summary>
        /// 
        /// </summary>
        [Description("Internal Server Error")]
        [EnumMember(Value = "1")]
        UnknownError = 500,

        /// <summary>
        /// 
        /// </summary>
        [Description("Bad Request")]
        [EnumMember(Value = "400")]
        BadRequest = 400,


        /// <summary>
        /// 
        /// </summary>
        [Description("An Authorize")]
        [EnumMember(Value = "401")]
        UnAuthorize = 401,


        /// <summary>
        /// 
        /// </summary>
        [Description("Not Found")]
        [EnumMember(Value = "404")]
        NotFound = 404,



    }
}
